<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Seeder;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'title' => 'Centros de Recursos',
                'titleEn' => 'Resource Centers',
                'introduction' => 'Moon crea espacios comunitarios en América Latina para almacenar materiales de emergencia y mejorar la infraestructura de viviendas vulnerables, fortaleciendo la resiliencia ante desastres naturales.',
                'introductionEn' => 'Moon creates community spaces in Latin America to store emergency materials and improve the infrastructure of vulnerable housing, strengthening resilience to natural disasters.',
                'description' => 'El desarrollo de vivienda social en América Latina y el Caribe (ALC) sigue siendo un gran reto. Ni se construye toda la necesaria, ni se apoya el mejoramiento de las que se encuentran en condiciones deficientes. Y no solo esto, cuando abordamos las posibles soluciones a este reto debemos considerar, además, la informalidad y la vulnerabilidad al cambio climático. Por ello Moon creo un espacio para comunidades, que permitirá almacenar materiales ante alguna emergencia o desastre natural. Infraestructura de quincha mejorada.',
                'descriptionEn' => 'The development of social housing in Latin America and the Caribbean (LAC) continues to be a major challenge. Not all that is needed is being built, nor is support being given to improve those that are in poor condition. And not only this, when addressing possible solutions to this challenge we must also consider informality and vulnerability to climate change. For this reason, Moon created a space for communities to store materials in the event of an emergency or natural disaster. Improved quincha infrastructure.',
                'headerImage' => 'https://develop.garzasoft.com/moon-group-backend/storage/app/public/projectSeeder/header_1_small-01.png'],
            [
                'title' => 'Alojamiento temporal (shelter): “Innovador, humanitario y aplicable”',
                'titleEn' => 'Temporary housing (shelter): “Innovative, humanitarian and applicable”.',
                'introduction' => 'Moon crea viviendas temporales de 18m² en madera, sostenibles y de bajo impacto ambiental, optimizadas para eficiencia energética y confort en situaciones de emergencia.',
                'introductionEn' => 'Moon creates sustainable, low environmental impact 18m² temporary wooden housing, optimized for energy efficiency and comfort in emergency situations.',
                'description' => 'No solo su diseño, sino la producción segura y su distribución, hacen de este un proyecto relevante. Esto demuestra el poder del diseño para responder a las condiciones en que estamos y transformarlas” solución - post emergencia, construimos viviendas temporales de madera de 18m2. La vivienda social sostenible es aquella en la que se consideran estrategias de sostenibilidad a lo largo de su ciclo de vida y que permite promover construcciones amigables con el medio ambiente, reduciendo el consumo de recursos naturales. En Moon tenemos en cuenta estas características: Uso de materiales con atributos de sostenibilidad, Disminución en los consumos de agua y energía, Uso de fuentes de energía alternativas, Aplicación de prácticas para minimizar los impactos negativos durante la obra, Diseño para maximizar el confort térmico y lumínico',
                'descriptionEn' => 'Not only its design, but the safe production and distribution make this a relevant project. This demonstrates the power of design to respond to the conditions we are in and transform them” solution - post emergency, we built 18m2 temporary wooden housing. Sustainable social housing is that which considers sustainability strategies throughout its life cycle and promotes environmentally friendly construction, reducing the consumption of natural resources. At Moon we take into account these characteristics: Use of materials with sustainability attributes, Decrease in water and energy consumption, Use of alternative energy sources, Application of practices to minimize negative impacts during construction, Design to maximize thermal and lighting comfort, and the use of renewable energy sources.',
                'headerImage' => 'https://develop.garzasoft.com/moon-group-backend/storage/app/public/projectSeeder/header_2_small-02.png'],
            [
                'title' => 'Sistemas de agua (Wash): "Servicios Sostenibles e innovadores de agua y Saneamiento"',
                'titleEn' => 'Water Systems (Wash): “Sustainable and Innovative Water and Sanitation Services”.',
                'introduction' => 'Nuestro proyecto lleva agua limpia y saneamiento sostenible a zonas rurales, promoviendo el acceso a servicios básicos como un derecho humano esencial.',
                'introductionEn' => 'Our project brings clean water and sustainable sanitation to rural areas, promoting access to basic services as an essential human right.',
                'description' => 'En el corazón de nuestra misión se encuentra el compromiso con las comunidades rurales, pilares fundamentales de nuestra sociedad, nuestro entorno ambiental y nuestro progreso económico. Reconocemos su invaluable contribución al cultivar nuestros alimentos, preservar nuestros recursos naturales y enriquecer nuestra diversidad cultural. Sin embargo, la realidad es desafiante. En las zonas rurales, la carencia de acceso a servicios básicos de agua, saneamiento e higiene (WASH) es alarmante. Ocho de cada diez hogares carecen de acceso a servicios básicos de agua, y seis de cada diez no disponen de saneamiento adecuado. Esta brecha en la universalización del agua y el saneamiento es una llamada urgente a la acción. Es por ello que, en nuestro proyecto de agua y saneamiento, nos dedicamos a cerrar esta brecha, llevando servicios limpios, asequibles y sostenibles a las comunidades rurales. Creemos que el acceso a agua potable y a instalaciones de saneamiento adecuadas es un derecho humano fundamental, esencial para la salud, el bienestar y el desarrollo integral de cada individuo y de la comunidad en su conjunto. Nuestro proyecto se enmarca en el acceso sustentable al agua en zonas rurales, sistemas de abastecimiento y saneamiento para comunidades.',
                'descriptionEn' => 'At the heart of our mission is our commitment to rural communities, fundamental pillars of our society, our environment and our economic progress. We recognize their invaluable contribution in growing our food, preserving our natural resources and enriching our cultural diversity. However, the reality is challenging. In rural areas, the lack of access to basic water, sanitation and hygiene (WASH) services is alarming. Eight out of ten households lack access to basic water services, and six out of ten lack adequate sanitation. This gap in the universalization of water and sanitation is an urgent call to action. That is why, in our water and sanitation project, we are dedicated to closing this gap by bringing clean, affordable and sustainable services to rural communities. We believe that access to clean water and adequate sanitation facilities is a fundamental human right, essential to the health, well-being and integral development of each individual and the community as a whole. Our project is framed within the framework of sustainable access to water in rural areas, supply and sanitation systems for communities.',
                'headerImage' => 'https://develop.garzasoft.com/moon-group-backend/storage/app/public/projectSeeder/header_3_small-03.png'],
            [
                'title' => 'Letrinas: "Sin sostenibilidad no hay saneamiento"',
                'titleEn' => 'Latrines: “No sustainability, no sanitation”.',
                'introduction' => 'Moon construye letrinas sostenibles para mejorar el saneamiento y prevenir enfermedades en comunidades sin acceso a agua.',
                'introductionEn' => 'Moon builds sustainable latrines to improve sanitation and prevent disease in communities without access to water.',
                'description' => '¿Cuál es la ubicación idónea para construir una letrina? ¿Cómo ventilarla? ¿Cómo hacer que los niños puedan usarla con facilidad? ¿Y las mujeres? ¿Qué materiales usar? Las respuestas varían en función de la cultura, el clima y la capacitación de los usuarios. Son factores que definen la sostenibilidad del saneamiento allí donde más falta hace: en la lucha contra la defecación al aire libre. La mayoría de las letrinas sanitarias funcionan sin agua, por lo que son considerados baños secos. Sirven principalmente para descomponer las excretas, ya que, al confinarlas, se reduce la posibilidad de que las fuentes de agua se contaminen y haya una transmisión de enfermedades gastrointestinales causadas por parásitos y microorganismos patógenos. Por ello Moon desarrolla la construcción de letrinas, Imprescindible para la salud y prevención de enfermedades. Estas pueden ser con pozo seco, ventilado, arrastre hidráulico o aboneras.',
                'descriptionEn' => 'What is the best location to build a latrine? How to ventilate it? How to make it easy for children to use? What about women? What materials to use? The answers vary depending on the culture, climate and training of the users. These are factors that define the sustainability of sanitation where it is most needed: in the fight against open defecation. Most sanitary latrines operate without water, so they are considered dry toilets. They serve mainly to decompose excreta, as confining them reduces the possibility of contamination of water sources and transmission of gastrointestinal diseases caused by parasites and pathogenic microorganisms. Therefore Moon develops the construction of latrines, essential for health and disease prevention. These can be with dry well, ventilated, hydraulic drag or composting.',
                'headerImage' => 'https://develop.garzasoft.com/moon-group-backend/storage/app/public/projectSeeder/header_4_slider-thumb2.png'],
            [
                'title' => 'Cocinas mejoradas: "Transición y evolución hacia combustibles más limpios y eficientes"',
                'titleEn' => 'Improved cookstoves: “Transition and evolution towards cleaner and more efficient fuels”.',
                'introduction' => 'Moon construye letrinas sostenibles para mejorar el saneamiento y prevenir enfermedades en comunidades sin acceso a agua.',
                'introductionEn' => 'Moon builds sustainable latrines to improve sanitation and prevent disease in communities without access to water.',
                'description' => 'Las cocinas mejoradas son un sustituto de los fogones tradicionales, los cuales son usados en zonas rurales en el Perú, que mejoran la calidad de vida de las personas al reducir la exposición a humos tóxicos y la carga de trabajo de sus usuarios, además aprovechan de una mejor manera el combustible contribuyendo a disminuir la emisión de gases de efecto invernadero. El uso de fuegos abiertos para cocinar es un problema mundial, especialmente en los países en vías de desarrollo. Casi tres billones de personas aún cocinan sobre fuegos abiertos con leña, carbón, residuos de la agricultura y estiércol. La Agencia Internacional de Energía estima que para el año 2030, 100 millones de personas más se sumarán a la práctica de uso de fuegos abiertos, quemando biomasa. Moon desarrolla un modelo constructivo que permite reducir el uso de combustible. Utilizando materiales de la zona, ambientales y socioculturales. De fácil uso para grupos vulnerables.',
                'descriptionEn' => "Improved cookstoves are a substitute for traditional stoves, which are used in rural areas in Peru, and improve people's quality of life by reducing exposure to toxic fumes and the workload of their users, as well as making better use of fuel, thus contributing to reducing greenhouse gas emissions. The use of open fires for cooking is a global problem, especially in developing countries. Nearly three billion people still cook over open fires with wood, charcoal, agricultural residues and dung. The International Energy Agency estimates that by 2030, 100 million more people will join the practice of using open fires, burning biomass. Moon develops a construction model that allows for a reduction in fuel use. Using local, environmental and socio-cultural materials. Easy to use for vulnerable groups.",
                'headerImage' => 'https://develop.garzasoft.com/moon-group-backend/storage/app/public/projectSeeder/header_4_slider-thumb2.png'],
        ];
        foreach ($data as $route) {
            Project::factory()->create([
                'title' => $route['title'],
                'titleEn' => $route['titleEn'],
                'introduction' => $route['introduction'],
                'introductionEn' => $route['introductionEn'],
                'description' => $route['description'],
                'descriptionEn' => $route['descriptionEn'],
                'headerImage' => $route['headerImage'],
            ]);
        }
    }
}
